(function(){
'use strict';
const URL='https://ixuxaqerdftadfnkxxui.supabase.co';
const KEY='sb_publishable_2Q42l50u-YjgBmu5xDvoAA_LUtLhm8j';
const sb=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:localStorage,storageKey:'family-finance-auth'}});
const rentAliases=new Set([
  '사업비','임대사업비','임대/사업비','임대중개수수료','임대/중개수수료',
  '임대전기수리비','임대/전기수리비','임대방충망수리비','임대/방충망수리비',
  '임대도배비','임대/도배비','임대바닥공사비','임대/바닥공사비','투자관련/인테리어비'
]);
const canon=v=>{
  const raw=String(v||'미분류').trim()||'미분류',compact=raw.replace(/\s+/g,'');
  if(raw==='미분류'||raw==='내부이체')return raw;
  if(raw==='외식'||raw==='식비/마트'||raw==='식비/편의점')return '식비';
  if(raw==='육아'||raw==='육아/교육'||raw==='육아비'||raw.startsWith('육아비/'))return '육아비';
  if(rentAliases.has(raw)||rentAliases.has(compact))return '투자관련';
  return raw.split('/')[0]?.trim()||raw;
};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const won=n=>Math.round(Math.abs(Number(n)||0)).toLocaleString('ko-KR')+'원';
let cache=new Map(),sortMode='amount',activeDetail=null,rowsById=new Map(),timer=null;
function period(){return {year:+document.getElementById('yearSelect')?.value,month:+document.getElementById('monthSelect')?.value};}
function bounds(y,m){return {start:new Date(y,m-1,1).toISOString(),end:new Date(y,m,1).toISOString()};}
async function txs(y,m){const k=`${y}-${m}`;if(cache.has(k))return cache.get(k);const p=(async()=>{const {start,end}=bounds(y,m),all=[];for(let off=0;;off+=1000){const {data,error}=await sb.from('transactions').select('id,occurred_at,source,account,merchant,category,amount,memo,is_fixed_expense').gte('occurred_at',start).lt('occurred_at',end).order('occurred_at',{ascending:false}).range(off,off+999);if(error)throw error;all.push(...(data||[]));if(!data||data.length<1000)break;}return all;})();cache.set(k,p);try{return await p}catch(e){cache.delete(k);throw e;}}
function impact(r){const a=Number(r.amount);if(!Number.isFinite(a)||a===0)return null;if(a<0)return Math.abs(a);if(a>0&&r.source==='toss_statement_refund')return-a;return null;}
function split(rows){let f=0,v=0;for(const r of rows){if(canon(r.category)==='내부이체')continue;const x=impact(r);if(x===null)continue;if(r.is_fixed_expense)f+=x;else v+=x;}return {f:Math.max(0,f),v:Math.max(0,v)};}
function style(){if(document.getElementById('settlementSafeStyles'))return;const s=document.createElement('style');s.id='settlementSafeStyles';s.textContent=`
.breakdown-row[data-safe-cat]{position:relative;cursor:pointer;padding-right:30px!important;border-radius:13px;touch-action:manipulation}.breakdown-row[data-safe-cat]::after{content:'›';position:absolute;right:9px;top:8px;color:#6f94ba;font-size:22px}.safe-back[hidden]{display:none!important}.safe-back{position:fixed;inset:0;z-index:11000;background:rgba(1,6,12,.8);backdrop-filter:blur(7px);display:flex;align-items:flex-end}.safe-sheet{width:100%;max-height:84vh;overflow:auto;background:linear-gradient(180deg,#0d1e31,#081421);border:1px solid #234c70;border-bottom:0;border-radius:28px 28px 0 0;padding:10px 18px calc(24px + env(safe-area-inset-bottom))}.safe-handle{width:42px;height:5px;border-radius:999px;background:#40536a;margin:2px auto 15px}.safe-head{display:flex;justify-content:space-between;gap:12px;padding-bottom:12px;border-bottom:1px solid var(--line2)}.safe-title{font-size:20px;font-weight:850}.safe-sub{font-size:11px;color:var(--muted);margin-top:4px}.safe-close{width:38px;height:38px;border:1px solid #294c6d;background:#102137;color:white;border-radius:13px;font-size:21px}.safe-sort{display:flex;gap:7px;padding:12px 0 8px}.safe-sort button{border:1px solid #284b6c;background:#0a1929;color:#8fa6bf;border-radius:999px;padding:7px 11px;font-size:11px;font-weight:760}.safe-sort button[aria-pressed=true]{background:#16446d;border-color:#4b9dff;color:white}.safe-row{position:relative;display:grid;grid-template-columns:1fr auto;gap:12px;padding:13px 20px 13px 2px;border-top:1px solid var(--line2);cursor:pointer}.safe-row::after{content:'›';position:absolute;right:2px;top:50%;transform:translateY(-50%);color:#5f82a5}.safe-merchant{font-size:14px;font-weight:780}.safe-meta{font-size:11px;color:var(--muted);margin-top:4px}.safe-fixed{color:#8abfff;font-weight:800}.safe-amt{font-size:14px;font-weight:800;color:#8abfff;white-space:nowrap}.safe-edit{z-index:11020}.safe-choice{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:16px;padding:15px;border:1px solid #294c6d;border-radius:16px;background:#091829}.safe-choice label{display:flex;align-items:center;gap:10px;font-size:15px;font-weight:820}.safe-choice input{appearance:none;-webkit-appearance:none;width:26px;height:26px;border:2px solid #64819e;border-radius:5px;background:#06111e;display:grid;place-content:center}.safe-choice input:before{content:'✓';font-size:18px;color:white;transform:scale(0)}.safe-choice input:checked{background:#347fbd;border-color:#65b1ee}.safe-choice input:checked:before{transform:scale(1)}.safe-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px}.safe-actions button{border:1px solid #315d83;background:#10253b;color:white;border-radius:13px;padding:12px;font-weight:800}.safe-actions .primary{background:#16446d}.safe-status{min-height:18px;font-size:11px;color:var(--green);text-align:right;margin-top:6px}`;document.head.appendChild(s);}
function ensureDetail(){let r=document.getElementById('safeCategoryDetail');if(r)return r;r=document.createElement('div');r.id='safeCategoryDetail';r.className='safe-back';r.hidden=true;r.innerHTML=`<section class="safe-sheet"><div class="safe-handle"></div><div class="safe-head"><div><div class="safe-title" id="safeTitle"></div><div class="safe-sub" id="safeSub"></div></div><button class="safe-close">×</button></div><div id="safeBody"></div></section>`;document.body.append(r);r.addEventListener('click',e=>{if(e.target===r||e.target.closest('.safe-close')){r.hidden=true;return}const b=e.target.closest('[data-sort]');if(b){sortMode=b.dataset.sort;renderDetail();return}const row=e.target.closest('[data-tx]');if(row)openEdit(rowsById.get(row.dataset.tx));});return r;}
function sorted(rows){const a=[...rows];if(sortMode==='latest')a.sort((x,y)=>new Date(y.occurred_at)-new Date(x.occurred_at));else a.sort((x,y)=>(Math.abs(impact(y)||0)-Math.abs(impact(x)||0))||(new Date(y.occurred_at)-new Date(x.occurred_at)));return a;}
function renderDetail(){if(!activeDetail)return;const root=ensureDetail(),rows=sorted(activeDetail.rows);rowsById=new Map(rows.map(r=>[String(r.id),r]));root.querySelector('#safeTitle').textContent=activeDetail.category;root.querySelector('#safeSub').textContent=`${activeDetail.year}년 ${activeDetail.month}월 · ${rows.length}건`;root.querySelector('#safeBody').innerHTML=`<div class="safe-sort"><button data-sort="amount" aria-pressed="${sortMode==='amount'}">금액 큰순</button><button data-sort="latest" aria-pressed="${sortMode==='latest'}">최신순</button></div>`+(rows.map(r=>{const d=new Date(r.occurred_at).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});const rawCat=String(r.category||'미분류').trim()||'미분류';return `<div class="safe-row" data-tx="${esc(r.id)}"><div><div class="safe-merchant">${esc(r.merchant||rawCat||'거래')}</div><div class="safe-meta">${esc(d)} · ${esc(r.account||r.source||'')} · ${esc(rawCat)}${r.is_fixed_expense?'<span class="safe-fixed"> · 고정지출</span>':''}</div></div><div class="safe-amt">${won(r.amount)}</div></div>`}).join('')||'<div class="safe-meta" style="padding:25px 0;text-align:center">거래내역이 없습니다.</div>');root.hidden=false;}
async function openCategory(category){const {year,month}=period();const root=ensureDetail();root.querySelector('#safeTitle').textContent=category;root.querySelector('#safeSub').textContent='불러오는 중';root.querySelector('#safeBody').innerHTML='<div class="safe-meta" style="padding:25px 0;text-align:center">거래내역을 불러오고 있습니다.</div>';root.hidden=false;try{const rows=(await txs(year,month)).filter(r=>canon(r.category)===category&&impact(r)!==null);activeDetail={category,year,month,rows};renderDetail()}catch(e){root.querySelector('#safeBody').textContent='불러오기 실패';}}
function ensureEdit(){let r=document.getElementById('safeFixedEdit');if(r)return r;r=document.createElement('div');r.id='safeFixedEdit';r.className='safe-back safe-edit';r.hidden=true;r.innerHTML=`<section class="safe-sheet"><div class="safe-handle"></div><div class="safe-head"><div><div class="safe-title" id="safeEditTitle">거래 설정</div><div class="safe-sub" id="safeEditSub"></div></div><button class="safe-close">×</button></div><div class="safe-choice"><label><input type="checkbox" id="safeFixedCheck"><span>고정지출</span></label><div class="safe-sub">체크하면 월별 결산<br>고정지출에 포함</div></div><div class="safe-actions"><button data-cancel>취소</button><button class="primary" data-save>저장</button></div><div class="safe-status" id="safeEditStatus"></div></section>`;document.body.append(r);r.addEventListener('click',e=>{if(e.target===r||e.target.closest('.safe-close')||e.target.closest('[data-cancel]'))r.hidden=true;if(e.target.closest('[data-save]'))saveEdit();});return r;}
function openEdit(tx){if(!tx)return;const r=ensureEdit();r.dataset.id=tx.id;r.querySelector('#safeEditTitle').textContent=tx.merchant||tx.category||'거래';r.querySelector('#safeEditSub').textContent=won(tx.amount);r.querySelector('#safeFixedCheck').checked=!!tx.is_fixed_expense;r.querySelector('#safeEditStatus').textContent='';r.hidden=false;}
async function saveEdit(){const r=ensureEdit(),id=r.dataset.id,check=r.querySelector('#safeFixedCheck').checked,status=r.querySelector('#safeEditStatus');status.textContent='저장 중…';const {data,error}=await sb.from('transactions').update({is_fixed_expense:check}).eq('id',id).select('id,is_fixed_expense').single();if(error){status.textContent='저장 실패';return}const row=rowsById.get(String(id));if(row)row.is_fixed_expense=!!data.is_fixed_expense;cache.clear();status.textContent='저장됨';setTimeout(()=>{r.hidden=true;renderDetail();patchFixed(true)},120);}
async function patchFixed(force=false){const title=[...document.querySelectorAll('#report h2.section-title')].find(x=>x.textContent.trim()==='고정지출 / 비고정지출'),card=title?.nextElementSibling;if(!card)return;const {year,month}=period(),key=`${year}-${month}`;if(!force&&card.dataset.safeFixed===key)return;card.dataset.safeFixed=key;try{const {f,v}=split(await txs(year,month)),vals=card.querySelectorAll('.split .value');if(vals[0])vals[0].textContent=won(f);if(vals[1])vals[1].textContent=won(v);card.querySelector('.unclassified')?.remove();const note=[...card.querySelectorAll('.small-note')].at(-1);if(note)note.textContent='개별 거래에서 고정지출을 체크한 항목만 고정지출로 집계합니다.';}catch(e){console.warn(e);}}
function enhance(){if(document.getElementById('monthlyTab')?.getAttribute('aria-selected')!=='true')return;for(const title of document.querySelectorAll('#report h2.section-title')){if(title.textContent.trim()!=='카테고리별 지출')continue;const card=title.nextElementSibling;if(!card)return;for(const row of card.querySelectorAll('.breakdown-row')){const name=row.querySelector('.breakdown-head span')?.textContent?.trim();if(name)row.dataset.safeCat=canon(name);}}patchFixed();}
function setup(){style();ensureDetail();ensureEdit();const report=document.getElementById('report');if(!report)return;report.addEventListener('click',e=>{const row=e.target.closest('[data-safe-cat]');if(row)openCategory(row.dataset.safeCat)});new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,30)}).observe(report,{childList:true,subtree:true});document.getElementById('refresh')?.addEventListener('click',()=>{cache.clear();setTimeout(()=>patchFixed(true),100)});['yearSelect','monthSelect'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>cache.clear()));enhance();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();